services:
  - docker

before_install:
  - docker pull miktex/miktex

script:
  - sudo gem install travis
  - docker run -ti -v $(pwd):/miktex/work -e MIKTEX_GID=$(id -g) -e MIKTEX_UID=$(id -u) miktex/miktex /bin/bash -c "mpm --update-db && pdflatex sample.tex"

after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add sample.pdf
  - git commit -m "[skip travis] Automatic PDF build from ${TRAVIS_COMMIT}"
  - git pull --rebase
  - git push --quiet origin HEAD
